services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siakers_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_NAME="SIAKERS RSJKO Engku Haji Daud"
      - APP_ENV=production
      - APP_KEY=base64:DywqJezUNOuozV8/YbIXbQ2fKbwMNrFmW1NvWmAp5Ug=
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=siaker_db
      - DB_USERNAME=siaker_user
      - DB_PASSWORD=siaker_password123
    depends_on:
      - db
    volumes:
      - storage_data:/var/www/html/storage

  db:
    image: mariadb:10.11
    container_name: siakers_db
    restart: always
    environment:
      MYSQL_DATABASE: siaker_db
      MYSQL_USER: siaker_user
      MYSQL_PASSWORD: siaker_password123
      MYSQL_ROOT_PASSWORD: root_password123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  storage_data:
